### ISSUE TITLE
BAD URI

### ISSUE THREAD

**Issue by 5nyper** [heroku-examples/ruby-websockets-chat-demo#10]
```
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)                                    
        from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'                                                                      
        from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'                                                                      
        from /root/ruby-websockets-chat-demo/middlewares/chat_backend.rb:15:in `initialize'                                                                    
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:86:in `new'                                                                    
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:86:in `block in use'                                                           
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:134:in `[]'                                                                    
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:134:in `block in to_app'                                                       
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:134:in `each'                                                                  
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:134:in `inject'                                                                
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:134:in `to_app'                                                                
        from config.ru:8:in `<main>'                                                                                                                           
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'                                                                   
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'                                                        
        from /usr/local/rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'                                                             
        from /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.6.0/lib/puma/configuration.rb:93:in `app'                                                              
        from /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.6.0/lib/puma/runner.rb:105:in `load_and_bind'                                                          
        from /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.6.0/lib/puma/single.rb:73:in `run'                                                                     
        from /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.6.0/lib/puma/cli.rb:442:in `run'                                                                       
        from /usr/local/rvm/gems/ruby-2.1.2/gems/puma-2.6.0/bin/puma:10:in `<top (required)>'                                                                  
        from /usr/local/rvm/gems/ruby-2.1.2/bin/puma:23:in `load'                                                                                              
        from /usr/local/rvm/gems/ruby-2.1.2/bin/puma:23:in `<main>'                                                                                            
        from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'                                                                             
        from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'                                               

```

Any fix?

**Comment by higgins777** [comment]
Ran into the same problem

**Comment by garethknowles** [comment]
This is due to running the app locally using foreman, as the `ENV["REDISCLOUD_URL"]` value doesn't exist.  You need to get a redis server running locally (see www.redis.io) and then setup the url as local `REDISCLOUD_URL=redis://localhost:6379` in `.env` 

There is actually a `.env.sample` in the directory, assuming the default redis-server is running, just rename this to `.env` and run `foreman start` to get going.
