### ISSUE TITLE
bad URI error

### ISSUE THREAD

**Issue by vdolbilov** [heroku-examples/ruby-websockets-chat-demo#9]
Hi, I get the following when running foreman start. Any ideas?

```
18:44:28 web.1  | started with pid 18702
18:44:29 web.1  | Puma starting in single mode...
18:44:29 web.1  | * Version 2.6.0, codename: Pantsuit Party
18:44:29 web.1  | * Min threads: 0, max threads: 16
18:44:29 web.1  | * Environment: development
18:44:29 web.1  | ! Unable to load application
18:44:29 web.1  | /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
18:44:29 web.1  |   from /Users/vdolbilov/Dev/ruby-websockets-chat-demo/middlewares/chat_backend.rb:15:in `initialize'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:86:in `new'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:86:in `block in use'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `[]'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `block in to_app'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `each'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `inject'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `to_app'
18:44:29 web.1  |   from config.ru:8:in `<main>'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/configuration.rb:93:in `app'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/runner.rb:105:in `load_and_bind'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/single.rb:73:in `run'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/cli.rb:442:in `run'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/bin/puma:10:in `<top (required)>'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/bin/puma:23:in `load'
18:44:29 web.1  |   from /usr/local/var/rbenv/versions/2.1.2/bin/puma:23:in `<main>'
18:44:29 web.1  | exited with code 1
18:44:29 system | sending SIGTERM to all processes
```

**Comment by vdolbilov** [comment]
```
18:44:28 web.1  | started with pid 18702
18:44:29 web.1  | Puma starting in single mode...
18:44:29 web.1  | * Version 2.6.0, codename: Pantsuit Party
18:44:29 web.1  | * Min threads: 0, max threads: 16
18:44:29 web.1  | * Environment: development
18:44:29 web.1  | ! Unable to load application
18:44:29 web.1  | /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split': bad URI(is not URI?):  (URI::InvalidURIError)
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
18:44:29 web.1  | 	from /Users/vdolbilov/Dev/ruby-websockets-chat-demo/middlewares/chat_backend.rb:15:in `initialize'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:86:in `new'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:86:in `block in use'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `[]'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `block in to_app'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `each'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `inject'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:134:in `to_app'
18:44:29 web.1  | 	from config.ru:8:in `<main>'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/configuration.rb:93:in `app'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/runner.rb:105:in `load_and_bind'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/single.rb:73:in `run'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/lib/puma/cli.rb:442:in `run'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/puma-2.6.0/bin/puma:10:in `<top (required)>'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/bin/puma:23:in `load'
18:44:29 web.1  | 	from /usr/local/var/rbenv/versions/2.1.2/bin/puma:23:in `<main>'
18:44:29 web.1  | exited with code 1
18:44:29 system | sending SIGTERM to all processes
```

**Comment by vdolbilov** [comment]
Turns out I needed to setup $REDISCLOUD_URL
